In [ ]:
# Tugas 8 PMDPM

# Alexis Divasonda Sigat Ngaing
# 210711407
# Kelas A

In [10]:
import pandas as pd

df_stroke = pd.read_csv('healthcare-dataset-stroke-data.csv')
# df_stroke = pd.DataFrame()
target = pd.DataFrame(data=df_stroke, columns=['stroke'])
df_stroke = df_stroke.drop(['stroke'], axis=1)
df_stroke = pd.concat([df_stroke, target], axis=1)
df_stroke.head(20)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
5,56669,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1
6,53882,Male,74.0,1,1,Yes,Private,Rural,70.09,27.4,never smoked,1
7,10434,Female,69.0,0,0,No,Private,Urban,94.39,22.8,never smoked,1
8,27419,Female,59.0,0,0,Yes,Private,Rural,76.15,NaN,Unknown,1
9,60491,Female,78.0,0,0,Yes,Private,Urban,58.57,24.2,Unknown,1
10,12109,Female,81.0,1,0,Yes,Private,Rural,80.43,29.7,never smoked,1
11,12095,Female,61.0,0,1,Yes,Govt_job,Rural,120.46,36.8,smokes,1
12,12175,Female,54.0,0,0,Yes,Private,Urban,104.51,27.3,smokes,1
13,8213,Male,78.0,0,1,Yes,Private,Urban,219.84,NaN,Unknown,1
14,5317,Female,79.0,0,1,Yes,Private,Urban,214.09,28.2,never smoked,1
15,58202,Female,50.0,1,0,Yes,Self-employed,Rural,167.41,30.9,never smoked,1
16,56112,Male,64.0,0,1,Yes,Private,Urban,191.61,37.5,smokes,1
17,34120,Male,75.0,1,0,Yes,Private,Urban,221.29,25.8,smokes,1
18,27458,Female,60.0,0,0,No,Private,Urban,89.22,37.8,never smoked,1
19,25226,Male,57.0,0,1,No,Govt_job,Urban,217.08,NaN,Unknown,1

In [17]:
# Data Cleansing

average = df_stroke['bmi'].mean()
average
df_stroke.bmi=(df_stroke.bmi.fillna(28.74))
df_stroke.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [ ]:
# Ubah data string menjadi data numeric

df_stroke["gender"].replace({"Male": 1, "Female": 0, "Other": -1}, inplace=True)
df_stroke["ever_married"].replace({"Yes": 1, "No": 0}, inplace=True)
df_stroke["work_type"].replace({'Private': 0, "Self-employed": 1, "Govt_job": 2, "children": 3, "Never_worked": 4}, inplace=True)
df_stroke["Residence_type"].replace({"Urban": 1, "Rural": 0}, inplace=True)
df_stroke["smoking_status"].replace({"smokes": 2, "formerly smoked": 1, "never smoked": 0, "Unknown": -1}, inplace=True)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, KFold, StratifiedKFold

X = df_stroke.drop(['id', 'stroke'], axis=1)
y = df_stroke['stroke']

logreg = LogisticRegression(max_iter=1000)

In [15]:
kfold = KFold(n_splits=3, shuffle=False)
skfold = StratifiedKFold(n_splits=3, shuffle=False)

scores3_kfold = cross_val_score(logreg, X.values, y.values, cv=kfold)
print("3-Fold Cross Validation Score: \n{}".format(scores3_kfold))

scores3_skfold = cross_val_score(logreg, X.values, y.values, cv=skfold)
print("3-Fold Stratified K-Fold Cross Validation Score: \n{}".format(scores3_skfold))

ValueError:
All the 3 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "/home/yamacat/.local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/yamacat/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1196, in fit
    X, y = self._validate_data(
  File "/home/yamacat/.local/lib/python3.10/site-packages/sklearn/base.py", line 584, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/home/yamacat/.local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1106, in check_X_y
    X = check_array(
  File "/home/yamacat/.local/lib/python3.10/site-packages/sklearn/utils/validation.py", line 879, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "/home/yamacat/.local/lib/python3.10/site-packages/sklearn/utils/_array_api.py", line 185, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
ValueError: could not convert string to float: 'Male'